### ISSUE TITLE
webui报错

### ISSUE THREAD

**Issue by KKKSQJ** [SHI-Labs/Matting-Anything#10]
我是windows平台，到webui界面，点击run，出现以下报错：
Something went wrong
Expecting value: line 1 column 1 (char 0)
![image](https://github.com/SHI-Labs/Matting-Anything/assets/37990345/4ae865df-1e2d-49ec-807e-0b1855143479)

**Comment by KKKSQJ** [comment]
请问该如何解决呀？

**Comment by chrisjuniorli** [comment]
can you reload the demo and try again, I just tested and it worked well on my side

**Comment by KKKSQJ** [comment]
刚刚莫名其妙的成功了一次，后来重启了一下，后出现了上述报错。会不会和我的梯度有关？我关掉了梯子后，连这个local 网址都打不开

**Comment by boz6336** [comment]
good go to sky

**Comment by EagleAiDi** [comment]
> 我是windows平台，到webui界面，点击run，出现以下报错： Something went wrong Expecting value: line 1 column 1 (char 0) ![image](https://user-images.githubusercontent.com/37990345/246150239-4ae865df-1e2d-49ec-807e-0b1855143479.png)

我遇到了一样的问题，请问你是怎么解决的？

**Comment by TigerSmat** [comment]
> 我是windows平台，到webui界面，点击run，出现以下报错： Something went wrong Expecting value: line 1 column 1 (char 0) ![image](https://private-user-images.githubusercontent.com/37990345/246150239-4ae865df-1e2d-49ec-807e-0b1855143479.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5OTk5NDcsIm5iZiI6MTcxMDk5OTY0NywicGF0aCI6Ii8zNzk5MDM0NS8yNDYxNTAyMzktNGFlODY1ZGYtMWUyZC00OWVjLTgwN2UtMGIxODU1MTQzNDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA1NDA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxNTZhMTU5NGIwYTEwZTQzM2VkOTQ5N2M2NGUwMGE3MDJhODVhMTM5ZWJmNjRjZDhlZTIxMzQ5N2UwMDExMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WPbnGC0I_35lfvy2ln8BgfCCkt15q7OEzygFrl8laz0)

我也是一模一样，请问你解决了嘛现在？

**Comment by TigerSmat** [comment]
已解决，这是python编码问题，加头文件 # -*-coding:utf-8 -*- 就可以解决
