### ISSUE TITLE
training code release

### ISSUE THREAD

**Issue by maoyj2333** [SHI-Labs/Matting-Anything#11]
Hi, thank you for the enlightening work. I found currently the mam model was based on SAM-b, and the extracted image feature is not compatible with the SAM-h, I am wondering is there any chances the training code or the mam SAM-h based checkpoint will be released ?

**Comment by chrisjuniorli** [comment]
Thanks for your interests in this work. We're still preparing the code release of the rest part and for now we only trained MAM on SAM-B, and this checkpoint is released [here](https://github.com/SHI-Labs/Matting-Anything/blob/main/INSTALL.md). We don't have plans for training MAM on SAM-H yet. Thanks!

**Comment by maoyj2333** [comment]
Trank you for your reply, looking forward to it
