### ISSUE TITLE
Request for the Distinctions646 dataset

### ISSUE THREAD

**Issue by maoyj2333** [SHI-Labs/Matting-Anything#15]
Hi,
I am trying to train the model on my own with the released code, but I got problem in getting dataset Distinctions646. The owner of the dataset doesn't reply my email, so could you pleses send me a copy of the dataset?

**Comment by chrisjuniorli** [comment]
I'm sorry, we couldn't send the copy of any dataset without the permission of the owners/authors of the datasets, thanks.

**Comment by boz6336** [comment]
😘😘😘😘😘😘
