### ISSUE TITLE
Thanks for wonderful word .Question about text prompt

### ISSUE THREAD

**Issue by baibizhe** [SHI-Labs/Matting-Anything#2]
Thanks for your wonderful word. The SAM model in your work seems to be acceptable for text prompt as shown in Figure2 .But SAM model seems  not to be fit with text prompt according to 
https://github.com/facebookresearch/segment-anything/issues/322
https://github.com/facebookresearch/segment-anything/issues/93
Do I misunderstand something here?

**Comment by chrisjuniorli** [comment]
Yes, SAM model didn't release the text prompt feature in their repo. We adopt the text prompt feature from Grounded-SAM: https://github.com/IDEA-Research/Grounded-Segment-Anything

**Comment by baibizhe** [comment]
Thanks

**Comment by baibizhe** [comment]
Hello. I want adopt the text prompt feature from Grounded-SAM to my SAM as well.  It would really appreciate if you could give some suggestions on how to  implementing adopt the text prompt feature from Grounded-SAM.

**Comment by chrisjuniorli** [comment]
The general idea is to send text prompt to GroundedDINO and it returns multiple boxes, then use them as box prompts for SAM. 
You may check the implementation here: https://github.com/SHI-Labs/Matting-Anything/blob/main/gradio_app.py

**Comment by baibizhe** [comment]
Thanks for you help .Hope you have a good weekend.
