### ISSUE TITLE
For Video?

### ISSUE THREAD

**Issue by p0mad** [SHI-Labs/Matting-Anything#3]

**Comment by chrisjuniorli** [comment]
Could you provide more descriptions about this issue, thanks

**Comment by p0mad** [comment]
@chrisjuniorli 
Is it possible to add video matting?
right now, images are able to be matted but how about videos?

**Comment by chrisjuniorli** [comment]
Yes, for video matting you can apply the same prompt to all frames as a hacky solution for now.
There is a third-party implementation for reference: https://huggingface.co/spaces/fffiloni/Video-Matting-Anything
