### ISSUE TITLE
Failed to build pycocotools - Python.h: No such file or directory

### ISSUE THREAD

**Issue by chrisbward** [SHI-Labs/Matting-Anything#6]
Hi I've set up a pyenv for 3.9 and followed the instructions, but has since failed, so I will investigate

**Comment by chrisbward** [comment]
Okay, after following instructions (here)[https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory], I was able to build pycocotools on Ubuntu with;

```
apt-get install python3.9-dev
```

Please update docs!

**Comment by chrisjuniorli** [comment]
We use anaconda to create virtual python environment in the docs and it's usually more sufficient / stable than pyenv.  Pyenv is not fully tested yet on our side.

**Comment by chrisbward** [comment]
Well, it worked. It's working in pyenv
