### ISSUE TITLE
pip install --upgrade diffusers[torch]

### ISSUE THREAD

**Issue by chrisbward** [SHI-Labs/Matting-Anything#7]
When executing the line `pip install --upgrade diffusers[torch]` I was met with the following error;

```
pip install --upgrade diffusers[torch]
zsh: no matches found: diffusers[torch]
```
I solved this by changing shell to `bash`, jumping in to the venv again and then re-running.

**Comment by eliorkfacetrom** [comment]
try: pip install --upgrade 'diffusers[torch]'

**Comment by chrisbward** [comment]
I changed shell to bash and it worked, so you might want to update

**Comment by zyc-bit** [comment]
add "setopt no_nomatch" in your .zshrc
